#!/bin/bash
# Virtualenv setup for Pushingkarma.com
# Copyright (c) 2015 PushingKarma. All rights reserved.

PS1="[pk] $_OLD_VIRTUAL_PS1"
export PYTHONPATH="$HOME/Projects/pushingkarma:$PYTHONPATH"
export DJANGO_SETTINGS_MODULE="pk.settings.settings"
source /home/mjs7231/Sources/django/extras/django_bash_completion
alias cdproject="cd $HOME/Projects/pushingkarma"
cdproject
