# Project Dependancies
[project]
name = 'pushingkarma'
version = '3.0.0'
description = 'Code that runs pushingkarma.com'
requires-python = '>=3.12'

dependencies = [
  'daphne',
  'exifread',
  'ofxtools',
  'praw',
  'pytz',
  'requests',
  'yfinance',
  'django==5.2.2',
  'django-cors-headers==4.7.0',
  'django-ninja==1.4.0',
  'django_searchquery @ git+https://github.com/pkkid/django-searchquery.git',
]

[project.optional-dependencies]
dev = [
  'fabric',
  'ipython',
  'keyring',
  'ruff',
]

[tool.ruff]
line-length = 125
lint.select = ['E','F','B','SIM']
lint.ignore = [
  'B007',     # Loop control variable not used within loop body
  'B008',     # Do not perform function call in argument defaults
  'E401',     # Multiple imports on one line
  'E701',     # Multiple statements on one line (colon)
  'E731',     # Do not assign a `lambda` expression, use a `def`
]
