#!/bin/bash
# This hook is run after this virtualenv is activated.

PROJECT="pushingkarma"
PS1="[$PROJECT] $_OLD_VIRTUAL_PS1"
export PYTHONPATH="$HOME/Projects:$PYTHONPATH"
export DJANGO_SETTINGS_MODULE="$PROJECT.settings.settings"
source /home/mjs7231/Sources/django/extras/django_bash_completion
alias cdproject="cd ~/Projects/$PROJECT"
cdproject
