# Install apt and pip packages
---
- name: Set timezone to US/Eastern
  tags: ['update']
  timezone:
    name: US/Eastern

- name: Create .bash_aliases
  tags: ['update']
  template:
    src: templates/bash_aliases.j2
    dest: ~/.bash_aliases

- name: Install Aptitude
  apt:
    name: aptitude

- name: Update System Packages
  tags: ['update']
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400
  notify: Restart Services

- name: Install System Packages
  tags: ['update']
  apt:
    name:
      - git
      - ipython3
      - python3-dev
      - python3-pip
      - sqlite3
      - vim
      - virtualenvwrapper
  notify: Restart Services

- name: Install requirements.pip
  tags: ['update', 'deploy']
  pip:
    requirements: '{{requirements}}'
    virtualenv: '{{virtualenv}}'
  notify: Restart Services

- name: Install postactivate Script
  tags: ['update']
  template:
    src: templates/postactivate.j2
    dest: '{{virtualenv}}/bin/postactivate'

- name: Create Log Directory
  file:
    path: '{{logs_dir}}'
    owner: www-data
    group: www-data
    state: directory

- name: Set Permissions in Log Directory
  tags: ['deploy']
  file: path={{logs_dir}} owner=www-data group=www-data mode=0755 state=directory recurse=yes
