# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.TextField(blank=True, default='')),
                ('sortindex', models.IntegerField(default=None)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('account', models.CharField(db_index=True, max_length=255)),
                ('accountfid', models.IntegerField(db_index=True)),
                ('trxid', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('payee', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, db_index=True, default='')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('accountfid', 'trxid')]),
        ),
    ]
