# Generated by Django 5.0.4 on 2025-03-12 03:12

import pk.utils.djutils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='import_rules',
            field=pk.utils.djutils.JSON5Field(default=None, null=True),
        ),
    ]
