# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
