# Generated by Django 3.0.4 on 2020-04-27 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='fid',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'fid')},
        ),
    ]
