# Generated by Django 5.0.4 on 2025-03-12 03:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='import_rules',
            field=models.JSONField(default=None, null=True),
        ),
    ]
