# Generated by Django 2.2 on 2020-02-12 03:10

from django.db import migrations


def create_uncategorized(apps, schema_editor):
    Category = apps.get_model('budget', 'Category')
    sortindex = Category.objects.order_by('-sortindex')[0].sortindex + 1
    Category.objects.create(name='Uncategorized', budget=0, sortindex=sortindex)


def populate_uncategorized(apps, schema_editor):
    Category = apps.get_model('budget', 'Category')
    Transaction = apps.get_model('budget', 'Transaction')
    uncategorized = Category.objects.get(name='Uncategorized')
    Transaction.objects.filter(category=None).update(category=uncategorized)


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_uncategorized),
        migrations.RunPython(populate_uncategorized),
    ]
