# Generated by Django 5.2 on 2025-04-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='import_rules',
            new_name='rules',
        ),
    ]
