# Generated by Django 5.2 on 2025-04-23 18:13
import django.db.models.deletion
from django.db import migrations, models
from pk.utils.django import ViewModelMixin
from pk.utils.django import create_views_sql


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_import_rules_account_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING,
                    primary_key=True, related_name='summary', serialize=False, to='budget.account')),
                ('total_spend', models.IntegerField()),
                ('total_income', models.IntegerField()),
                ('avg_spend_per_month', models.IntegerField()),
                ('avg_income_per_month', models.IntegerField()),
                ('transactions_this_year', models.IntegerField()),
                ('spend_this_year', models.IntegerField()),
                ('income_this_year', models.IntegerField()),
                ('avg_transactions_per_month_this_year', models.IntegerField()),
                ('avg_spend_per_month_this_year', models.IntegerField()),
                ('avg_income_per_month_this_year', models.IntegerField()),
            ],
            options={
                'db_table': 'budget_account_summary',
                'managed': False,
            },
            bases=(models.Model, ViewModelMixin),
        ),
        migrations.RunSQL(create_views_sql()),
    ]
