# Generated by Django 2.2 on 2020-03-02 16:29

from django.db import migrations, models
import pk.apps.budget.models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_create_uncategorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=None, on_delete=models.SET(pk.apps.budget.models.get_uncategorized), to='budget.Category'),
        ),
    ]
