# Generated by Django 5.0.4 on 2025-03-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_import_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='import_rules',
            field=models.JSONField(default=None, null=True),
        ),
    ]
