# Generated by Django 3.0.4 on 2020-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200427_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exclude_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='exclude_totals',
            field=models.BooleanField(default=False),
        ),
    ]
