# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:37
from __future__ import unicode_literals
from django.db import migrations
from django.conf import settings


def create_accounts(apps, schema_editor):
    Account = apps.get_model('budget', 'Account')
    for fid, a in settings.BUDGET_ACCOUNTS.items():
        account = Account(fid=fid, name=a['name'], type=a['type'], payee=a.get('payee',''))
        account.save()


def link_accounts(apps, schema_editor):
    Account = apps.get_model('budget', 'Account')
    Transaction = apps.get_model('budget', 'Transaction')
    accountids = dict(Account.objects.values_list('fid', 'id'))
    for trx in Transaction.objects.all():
        trx.accountfk_id = accountids[trx.accountfid]
        trx.save()


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0004_auto_20171031_1935'),
    ]
    operations = [
        migrations.RunPython(create_accounts),
        migrations.RunPython(link_accounts),
    ]
