# Generated by Django 5.1.7 on 2025-03-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_account_options_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balancedt',
            new_name='balance_updated',
        ),
    ]
