# Generated by Django 3.0.4 on 2020-05-09 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200502_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_payee',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
