# Generated by Django 3.0.4 on 2020-05-09 18:30

from django.db import migrations


def set_original_values(apps, schema_editor):
    Transaction = apps.get_model('budget', 'Transaction')
    for obj in Transaction.objects.all():
        obj.original_date = obj.date
        obj.original_payee = obj.payee
        obj.original_amount = obj.amount
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0005_auto_20200509_1430'),
    ]
    operations = [
        migrations.RunPython(set_original_values, migrations.RunPython.noop)
    ]
