# Generated by Django 5.1.7 on 2025-03-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_rename_balancedt_account_balance_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sortindex',
            new_name='sortid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='category',
            name='comment',
        ),
    ]
