# Generated by Django 5.1.7 on 2025-03-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_rename_sortindex_category_sortid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='exclude_budget',
            new_name='exclude',
        ),
    ]
