# Generated by Django 3.0.4 on 2020-05-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20200509_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='memo',
        ),
    ]
