# Generated by Django 5.1.7 on 2025-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_rename_exclude_budget_category_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sortid',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='category',
            name='sortid',
            field=models.IntegerField(default=9999),
        ),
    ]
