# Generated by Django 3.0.4 on 2020-05-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_remove_transaction_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='exclude_totals',
        ),
    ]
