# Generated by Django 3.0.4 on 2021-08-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_remove_category_exclude_totals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyValue',
        ),
    ]
