# Main Ansible Playbook File
#
# Example Usage:
#  > ansible-playbook -i inventory.ini playbook.yml
#  > ansible-playbook -i inventory.ini playbook.yml --tags=deploy
---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/upload.yml
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/django.yml
    - import_tasks: tasks/certbot.yml
    - import_tasks: tasks/redis.yml
    - import_tasks: tasks/daphne.yml
    - import_tasks: tasks/nginx.yml

  handlers:
    - name: Restart Redis
      service:
        name: redis
        state: restarted

    - name: Restart Services
      service:
        name: '{{item}}'
        state: restarted
      with_items:
        - nginx
        - daphne
