# Generated by Django 5.1.7 on 2025-04-18 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('info', models.JSONField(null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TickerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.ticker')),
            ],
            options={
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.AddField(
            model_name='ticker',
            name='lastday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stocks.tickerhistory'),
        ),
    ]
