# Generated by Django 5.2 on 2025-04-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker',
            new_name='id',
        ),
    ]
