# Generated by Django 2.0 on 2018-12-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tags',
            field=models.CharField(blank=True, help_text='space delimited', max_length=255),
        ),
    ]
