# Generated by Django 5.0.4 on 2025-03-12 17:26

import django.db.models.deletion
import pk.utils.djutils
from django.db import migrations, models


def copy_tickers(apps, schema_editor):
    Stock = apps.get_model('stocks', 'Stock')
    Ticker = apps.get_model('stocks', 'Ticker')
    for stock in Stock.objects.all():
        ticker = Ticker(ticker=stock.ticker, tags=stock.tags)
        ticker.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5, unique=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('info', pk.utils.djutils.JSON5Field(null=True)),
            ],
        ),
        migrations.AlterModelOptions(name='stock', options={'get_latest_by': 'modified'}),
        migrations.AlterField(model_name='stock', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.CreateModel(
            name='TickerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ticker')),
            ],
        ),
        migrations.RunPython(copy_tickers),
        migrations.DeleteModel(name='Stock'),
    ]
