# Generated by Django 2.0 on 2018-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
