# Generated by Django 5.0.4 on 2025-03-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_new_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tickerhistory',
            unique_together={('ticker', 'date')},
        ),
    ]
