# Generated by Django 5.0.4 on 2025-03-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_add_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='info',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
