# Generated by Django 5.1.7 on 2025-03-20 01:18

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_bad_tickers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='ticker',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='tickerhistory',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.ticker'),
        ),
    ]
