# Generated by Django 5.1.7 on 2025-03-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_ticker_options_ticker_created_ticker_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
