# Generated by Django 5.1.7 on 2025-03-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_ticker_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='lastday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stocks.tickerhistory'),
        ),
    ]
