# Generated by Django 5.1.7 on 2025-03-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_ticker_lastday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
