# Generated by Django 3.0.4 on 2020-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200320_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
